name: 'Terraform Destroy'

on: workflow_dispatch

permissions:
  contents: read

jobs:

  terraform:
    name: 'Terraform Destroy'
    env:
      # The command AZ Login only works with interactive authentication by users, not by automated service principals.
      # Therefore, we must declare the authentication settings as environment variables in order for Terraform to pick them up.
      ARM_CLIENT_ID: '${{ secrets.ARM_CLIENT_ID }}'
      ARM_CLIENT_SECRET: '${{ secrets.ARM_CLIENT_SECRET }}'
      ARM_TENANT_ID: '${{ secrets.ARM_TENANT_ID }}'
      ARM_SUBSCRIPTION_ID: '${{ secrets.ARM_SUBSCRIPTION_ID }}'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

      # Deploy infrastructure changes
    - name: Terraform Destroy
      run: terraform destroy -auto-approve -input=false
